' Base64.brs — btoa/atob polyfill
' Generated by svelte-roku compiler v0.6

function SvelteRoku_btoa(s as String) as String
  ba = CreateObject("roByteArray")
  ba.FromAsciiString(s)
  return ba.ToBase64String()
end function

function SvelteRoku_atob(s as String) as String
  ba = CreateObject("roByteArray")
  ba.FromBase64String(s)
  return ba.ToAsciiString()
end function
