' Base64.brs — btoa/atob polyfill
' Generated by svelte-roku compiler v0.6

function SvelteRoku_btoa(str as String) as String
  ba = CreateObject("roByteArray")
  ba.FromAsciiString(str)
  return ba.ToBase64String()
end function

function SvelteRoku_atob(str as String) as String
  ba = CreateObject("roByteArray")
  ba.FromBase64String(str)
  return ba.ToAsciiString()
end function
