export const RUNTIME_FILES = [
  "Promise.brs",
  "Fetch.brs",
  "FetchTask.brs",
  "FetchTask.xml",
  "MicrotaskQueue.brs",
  "Stdlib.brs",
  "Timers.brs",
  "Storage.brs",
  "DatePolyfill.brs",
  "URLPolyfill.brs",
  "Base64.brs",
  "EventTarget.brs",
  "FetchAPI.brs",
  "Collections.brs",
] as const;
